apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  selector:
    matchLabels:
      run: be
  template:
    metadata:
      labels:
        run: be
    spec:
      containers:
      - name: be
        image: rizqia/demo-22:0.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: be-svc
  labels:
    run: be-svc
spec:
  selector:
    run: be
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer
